id: helloParametrizedScheduled
namespace: prod
description: |
  This flow takes runtime-specific input and uses it to log a message to the console.
  The flow is scheduled to run every minute.

inputs:
  - name: user
    type: STRING
    defaults: Data Engineer
    required: false

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello {{ inputs.user }} from Kestra!

triggers:
  - id: defaultInputsSchedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/15 * * * *"
    inputs:
     name: user
  - id: customInputsSchedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
    inputs:
     name: user
     value: minutely flow