name: Publish a container image to ghcr.io

on:
  schedule:
    - cron: '0 9 * * MON'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "kestra-io/pydata" # ${{ github.repository }}

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Log in to Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          file: "pydata.Dockerfile"
